# Generated by Django 2.2.24 on 2021-06-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='标题')),
                ('desc', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='描述')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('lover', models.ManyToManyField(blank=True, related_name='love_blog', to=settings.AUTH_USER_MODEL, verbose_name='点赞人')),
            ],
        ),
    ]
